// File generated by Antigravity.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKTLHElqKHj0KxQTIYYh9lCiAFmcSxraE',
    appId: '1:724842455682:android:a0a31f16bc27a3ffbfca9b',
    messagingSenderId: '724842455682',
    projectId: 'jodeals-eaec4',
    storageBucket: 'jodeals-eaec4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKTLHElqKHj0KxQTIYYh9lCiAFmcSxraE',
    appId: '1:724842455682:ios:cd5169a9414b2d18fca9b',
    messagingSenderId: '724842455682',
    projectId: 'jodeals-eaec4',
    storageBucket: 'jodeals-eaec4.firebasestorage.app',
    iosBundleId: 'com.jodealz.app',
  );
}
